SET BAIL ON;
SET NAMES UTF8;

INSERT INTO ESTADO (ID, NOME, UF) VALUES (1, 'Minas Gerais', 'MG');
INSERT INTO ESTADO (ID, NOME, UF) VALUES (2, 'São Paulo', 'SP');
INSERT INTO ESTADO (ID, NOME, UF) VALUES (3, 'Rio de Janeiro', 'RJ');
INSERT INTO ESTADO (ID, NOME, UF) VALUES (4, 'Bahia', 'BA');

INSERT INTO CIDADE (ID, NOME, ESTADOID) VALUES (1, 'Belo Horizonte', 1);
INSERT INTO CIDADE (ID, NOME, ESTADOID) VALUES (2, 'Uberlândia', 1);
INSERT INTO CIDADE (ID, NOME, ESTADOID) VALUES (3, 'São Paulo', 2);
INSERT INTO CIDADE (ID, NOME, ESTADOID) VALUES (4, 'Campinas', 2);
INSERT INTO CIDADE (ID, NOME, ESTADOID) VALUES (5, 'Rio de Janeiro', 3);
INSERT INTO CIDADE (ID, NOME, ESTADOID) VALUES (6, 'Niterói', 3);
INSERT INTO CIDADE (ID, NOME, ESTADOID) VALUES (7, 'Salvador', 4);
INSERT INTO CIDADE (ID, NOME, ESTADOID) VALUES (8, 'Feira de Santana', 4);
COMMIT;
